name: Build image

on:
  pull_request: { branches: ["master"] }
  push:
    branches: ["master"]
    tags: [ "*" ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files in the src folders
        id: changed-files-src
        uses: tj-actions/changed-files@v43
      - name: Cancel if there are no code changes
        if: steps.changed-files-src.outputs.any_changed == 'false'
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: generate-image-tag
        name: Generate Image Tag
        env:
          ref_name: "${{ github.ref_name }}"
          head_ref: "${{ github.head_ref }}"
        run: |
          head_ref="${head_ref//\//-}"
          head_ref="${head_ref//./-}"
          head_ref="${head_ref//_/-}"
          ref_name="${head_ref:-${ref_name/main/latest}}"
          ref_name="${ref_name:0:32}"
          ref_name="${ref_name%-}"
          ref_name="$(echo "$ref_name" | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=imageTag::${ref_name#v}"
      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          registry-url: 'https://npm.pkg.github.com/'
      - run: npm ci --legacy-peer-deps
      - run: npm run build
        env:
          CI: false
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/image:${{ steps.generate-image-tag.outputs.imageTag }}
            ghcr.io/${{ github.repository }}/image:${{ github.event.pull_request.head.sha || github.sha }}